### ISSUE TITLE
UI upscaling replaces text with blocks when increased too much

### ISSUE THREAD

**Issue by terencode** [OpenMusicKontrollers/moony.lv2#12]
I wanted to have bigger text in the editor so I used Ctrl+scroll wheel.
Unfortunately, It is quite slow and resizes all the UI fonts and not just the one within the editor.
Maybe it would be better to let the plugin decide to resize the UI based on window geometry change events and only allow the user to change the font size within the editor.

The main issue is that at some point in increasing the UI size, the text will become some sort of blocks as demonstrated in the following video: 

![Peek 2019-11-07 21-01](https://user-images.githubusercontent.com/12665563/68423236-fa5d4380-01a1-11ea-9083-021f820a8b15.gif)

**Comment by ventosus** [comment]
Thanks for reporting.

> Unfortunately, It is quite slow and resizes all the UI fonts and not just the one within the editor.

This is intended, this just sets a scaling factor for everything (workaround for HiDPI displays).

> Maybe it would be better to let the plugin decide to resize the UI based on window geometry
> change events and only allow the user to change the font size within the editor.

Yes, I've had something similar in mind. Instead of font size, it'll most probably be number of rows and columns instead.

> The main issue is that at some point in increasing the UI size, the text will become some sort of 
> blocks as demonstrated in the following video:

I was able to reproduce this. Most probably a bug in the nuklear toolkit used underneath.

A next moony release will most probably have a completely new UI, I'll not invest any time in this, though.

p.s. moony has an alternate UI (needs to be enabled at compile-time), which just opens your favorite editor to edit the scripts and injects them at save, maybe that's something for you...

**Comment by terencode** [comment]
Ok, thanks for your answers. I'll try this alternate UI thing which will be a good enough workaround for meI think.

Should I close the issue? Or you will close it when the new UI is done?

**Comment by ventosus** [comment]
> Should I close the issue? Or you will close it when the new UI is done?

I'll keep it open, so I don't forget.
