### ISSUE TITLE
At some font sizes, the last log entry becomes hidden

### ISSUE THREAD

**Issue by milkmiruku** [OpenMusicKontrollers/moony.lv2#8]
I noticed this when I had the font enlarged, then I reduced the size, the last entry came back, then I reduced it some more and it became hidden again.

**Comment by ventosus** [comment]
What you see here is that scroll positions are not recalculated upon UI resize.

There's just no way to fix that, you need to manually rescroll.

Instead of manually resizing the UI, you can:
* set environmental variable NK_SCALE=1.2 (or to whatever multiplier you want)
* set Xft.dpi [1] to the proper DPI in your ~/.Xresources (by default 96 is assumed)

[1] https://wiki.archlinux.org/index.php/HiDPI#X_Resources
